
package Tienda_inventario;

import com.itextpdf.text.Chunk;
import java.sql.PreparedStatement;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.sql.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.util.Set;

public class Boleta extends javax.swing.JInternalFrame {
 Conexion con = new Conexion();
 public int nom;  
    public Boleta() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui =(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        jFecha.setText(FechaActual());
        jVerifyStock.setVisible(false);
    }

    public static String FechaActual(){
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("YYY/MM/dd");//"dd/MM/YYYY"
        return formatoFecha.format(fecha);
    }
    
    public void Precio(){
        int op1=jComboBox1.getSelectedIndex();
        String i;
         try{
             String SQL = "select PrecioUni from productos where Nom_Produc = '" + String.valueOf(jComboBox1.getItemAt(op1)) + "'";
             Statement stmt = con.con.createStatement();
             ResultSet rs = stmt.executeQuery(SQL);
             while(rs.next()){
                 jLabel14.setText(rs.getString("PrecioUni"));
             }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error " + e);
       }
    }
    public void NumBoleta(){
         try{
             String SQL = "SELECT MAX(NumBoleta) AS id FROM boleta";
             Statement stmt = con.con.createStatement();
             ResultSet rs = stmt.executeQuery(SQL);
             while(rs.next()){
                 jNumBoleta.setText(rs.getString("id"));
             }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error " + e);
       }
        
    }
     public void guardarBoleta(){
        try{
            String SQL = "insert into boleta (CodEmple, Cliente, DNI, Fecha, Nom_Produc, Cantidad) values (?,?,?,?,?,?)";
            PreparedStatement pst = con.con.prepareStatement(SQL);
            pst.setString(1, jCod.getText());
            pst.setString(2, jCliente.getText());
            pst.setString(3, jDNI.getText());
            pst.setString(4, jFecha.getText());
            nom=jComboBox1.getSelectedIndex();
            pst.setString(5, jComboBox1.getItemAt(nom));
            pst.setDouble(6, Integer.parseInt(jCantidad.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(null, "Boleta Guardada");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Revise el código del empleado");
        }
    }
     
     public void restringirStock(){
        try{
             String SQL = "SELECT Stock from productos where Nom_Produc = '"+producto+"'";
             Statement stmt = con.con.createStatement();
             ResultSet rs = stmt.executeQuery(SQL);
             while(rs.next()){
                jVerifyStock.setText(rs.getString("Stock"));
             }     
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error " + e);
       } 
     }
     
    public ArrayList<String> llenar_combo(){
        ArrayList<String> lista = new  ArrayList<String>();     
        String SQL = "SELECT * FROM PRODUCTOS";
        try{
        Statement stmt = con.con.createStatement();
         ResultSet rs = stmt.executeQuery(SQL);
            
          while(rs.next()){
               lista.add(rs.getString("Nom_Produc")); 
         }
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error " + e);
       }
 return lista;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCliente = new javax.swing.JTextField();
        jDNI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCantidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCod = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        jNumBoleta = new javax.swing.JTextField();
        jVerifyStock = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setPreferredSize(new java.awt.Dimension(630, 500));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel2.setText("CLIENTE:");

        jLabel3.setText("DNI:");

        jCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("FECHA:");

        jLabel5.setText("PRODUCTO:");

        jLabel6.setText("CANTIDAD:");

        jLabel7.setText("SUBTOTAL:");

        jLabel8.setText("IGV:");

        jLabel9.setText("TOTAL:");

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecione uno--" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel10.setText(" ");

        jLabel11.setText(" ");

        jLabel12.setText(" ");

        jLabel13.setText("CODIGO:");

        jLabel14.setText("         ");

        jLabel15.setText("PRECIO:");

        btnGenerar.setText("GENERAR BOLETA");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jNumBoleta.setEditable(false);
        jNumBoleta.setBackground(new java.awt.Color(204, 204, 204));
        jNumBoleta.setText(" ");

        jVerifyStock.setText("    ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addGap(162, 162, 162)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnGenerar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCod, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(282, 282, 282))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(32, 32, 32)
                                            .addComponent(jLabel14)
                                            .addGap(251, 251, 251)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(58, 58, 58)))
                            .addComponent(jNumBoleta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jVerifyStock)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jNumBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jVerifyStock)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       Precio();
    }//GEN-LAST:event_jComboBox1ActionPerformed
    public int cantidad;
    public double precio;
    public String producto;
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
      cantidad = Integer.parseInt(jCantidad.getText());
      precio = Double.parseDouble(jLabel14.getText());
    
      Calcular boleta1 = new Calcular(cantidad, precio);
   
      jLabel10.setText(String.valueOf(boleta1.subTotal()));
      jLabel11.setText(String.valueOf(boleta1.IGV()));
      jLabel12.setText(String.valueOf(boleta1.Total()));
      
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void jClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClienteActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      cantidad = Integer.parseInt(jCantidad.getText());
      nom= jComboBox1.getSelectedIndex();
      producto =  String.valueOf(jComboBox1.getItemAt(nom));
      
      restringirStock();
      
      int st = Integer.parseInt(jVerifyStock.getText());
      int posibleSt = st - cantidad;
      if (posibleSt>0){
        ActualizarStock ac = new ActualizarStock(producto, cantidad);
        ac.nuevoStock();
        guardarBoleta();
        NumBoleta();    
      }else{
        JOptionPane.showMessageDialog(null, "El stock actual no es suficiente");  
      }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       
 
      
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        jComboBox1.removeAllItems();
        ArrayList<String> lista = new  ArrayList<String>();
        lista = llenar_combo();
        for (int i = 0; i < lista.size(); i++) {
            jComboBox1.addItem(lista.get(i));
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
       Document documento = new Document();
       int Boleta = Integer.parseInt(jNumBoleta.getText());
       try{
           String ruta = System.getProperty("user.home");
           PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Reporte.pdf"));
           documento.open();
           Paragraph boleta = new Paragraph("NÚMERO DE BOLETA: " + Boleta);
           boleta.setAlignment(Element.ALIGN_RIGHT);
           documento.add(boleta);
           documento.add(Chunk.NEWLINE);
           documento.add(new Paragraph("CLIENTE: " + jCliente.getText()));
           documento.add(new Paragraph("DNI: " + jDNI.getText()));
           documento.add(new Paragraph("FECHA: " + jFecha.getText()));
           documento.add(Chunk.NEWLINE);
           PdfPTable table = new PdfPTable(6);
           table.addCell("Producto");
           table.addCell("Precio");
           table.addCell("Cantidad");
           table.addCell("Subtotal");
           table.addCell("IGV");
           table.addCell("Total");
           try{
            String SQL = "select b.Nom_Produc as Producto, p.PrecioUni, b.Cantidad, round(p.PrecioUni*b.Cantidad,2) as SubTotal, round((p.PrecioUni*b.Cantidad) * 0.18, 2) as IGV, round((p.PrecioUni*b.Cantidad)+((p.PrecioUni*b.Cantidad) * 0.18),2) as Total from boleta b INNER JOIN productos p on (p.Nom_Produc = b.Nom_Produc) INNER JOIN empleado e on (e.CodEmple= b.CodEmple) where b.NumBoleta = '"+Boleta+"'";
            Statement stmt = con.con.createStatement();
            ResultSet rs = stmt.executeQuery(SQL); 
            
            if(rs.next()){
                do{
                    table.addCell(rs.getString(1));
                    table.addCell(rs.getString(2));
                    table.addCell(rs.getString(3));
                    table.addCell(rs.getString(4));
                    table.addCell(rs.getString(5));
                    table.addCell(rs.getString(6));
                }while(rs.next());
                documento.add(table);
            }
           }catch(Exception e){
               System.out.println(e);
           }
           documento.add(Chunk.NEWLINE);
           Paragraph pie = new Paragraph("¡GRACIAS POR SU COMPRA, VUELVA PRONTO!");
           pie.setAlignment(Element.ALIGN_CENTER);
           documento.add(pie);
            documento.close();
            JOptionPane.showMessageDialog(null, "Boleta PDF guardada");
            
       }catch (Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_btnGenerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField jCantidad;
    private javax.swing.JTextField jCliente;
    private javax.swing.JTextField jCod;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jDNI;
    private javax.swing.JTextField jFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNumBoleta;
    private javax.swing.JLabel jVerifyStock;
    // End of variables declaration//GEN-END:variables
}
